[package]
name = "steamworks-command"
version = "0.1.0"
edition = "2024"

[dependencies]
steamworks = "0.11.0"
tokio = { version = "1.44.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = true        # 链接时优化
codegen-units = 1 # 提升优化效果
panic = "abort"   # 减小体积
strip = true      # 移除调试符号
opt-level = "z"   # 最小体积优化
